<?xml version="1.0" ?>
<project xmlns="http://maven.apache.org/POM/4.0.0">
  <modelVersion>4.0.0</modelVersion>
  <parent>
    <groupId>ch.so.agi</groupId>
    <artifactId>hop-raster-type-plugin-parent</artifactId>
    <version>0.1.0-SNAPSHOT</version>
  </parent>
  <artifactId>hop-raster-geotools</artifactId>
  <dependencies>
    <dependency>
      <groupId>ch.so.agi</groupId>
      <artifactId>hop-geometry-type</artifactId>
      <version>${hop.geometry.type.version}</version>
      <scope>provided</scope>
    </dependency>
    <dependency>
      <groupId>ch.so.agi</groupId>
      <artifactId>hop-raster-core</artifactId>
      <version>${project.version}</version>
    </dependency>
    <dependency>
      <groupId>org.geotools</groupId>
      <artifactId>gt-geotiff</artifactId>
      <scope>provided</scope>
    </dependency>
    <dependency>
      <groupId>org.geotools</groupId>
      <artifactId>gt-epsg-hsql</artifactId>
      <scope>provided</scope>
    </dependency>
    <dependency>
      <groupId>tech.units</groupId>
      <artifactId>indriya</artifactId>
      <scope>provided</scope>
    </dependency>
    <dependency>
      <groupId>org.locationtech.jts</groupId>
      <artifactId>jts-core</artifactId>
      <scope>provided</scope>
    </dependency>
    <dependency>
      <groupId>org.junit.jupiter</groupId>
      <artifactId>junit-jupiter</artifactId>
      <scope>test</scope>
    </dependency>
    <dependency>
      <groupId>org.assertj</groupId>
      <artifactId>assertj-core</artifactId>
      <scope>test</scope>
    </dependency>
  </dependencies>
  <build>
    <plugins>
      <plugin>
        <artifactId>maven-compiler-plugin</artifactId>
      </plugin>
      <plugin>
        <artifactId>maven-surefire-plugin</artifactId>
      </plugin>
    </plugins>
  </build>
</project>
